exclude: [sass, .gitignore, node_modules]
highlighter: pygments
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      types: "pages"
    values:
      layout: "default"
